name:                terminal
synopsis:            Portable terminal interaction library
version:             0.2.0.0
github:              "lpeterse/haskell-terminal"
license:             BSD3
author:              "Lars Petersen"
maintainer:          "info@lars-petersen.net"
copyright:           "2018 Lars Petersen"
category:            Terminal

extra-source-files:
- README.md
- CHANGELOG.md
- LICENSE
- platform/posix/cbits/hs_terminal.c
- platform/posix/include/hs_terminal.h
- platform/posix/src/System/Terminal/Platform.hsc
- platform/windows/cbits/hs_terminal.c
- platform/windows/include/hs_terminal.h
- platform/windows/src/System/Terminal/Platform.hsc

description:         Please see the README on Github at <https://github.com/lpeterse/haskell-terminal#readme>

dependencies:
- base >= 4.7 && < 5
- async
- bytestring
- exceptions >= 0.10.0
- prettyprinter
- stm
- text
- transformers

default-extensions:
- LambdaCase
- MultiWayIf
- BlockArguments
- OverloadedStrings
- GeneralizedNewtypeDeriving
- TupleSections

library:
  ghc-options: -Wall -fwarn-incomplete-patterns
  source-dirs: src
  exposed-modules:
    - System.Terminal
    - System.Terminal.Internal
  other-modules:
    - System.Terminal.Decoder
    - System.Terminal.Encoder
    - System.Terminal.MonadInput
    - System.Terminal.MonadPrinter
    - System.Terminal.MonadScreen
    - System.Terminal.MonadTerminal
    - System.Terminal.Pretty
    - System.Terminal.Terminal
    - System.Terminal.TerminalT
    - System.Terminal.Platform
    - System.Terminal.Virtual
  when:
  - condition: os(windows)
    then:
      source-dirs:
        - src
        - platform/windows/src
      include-dirs:
        - platform/windows/include
      c-sources:
        - platform/windows/cbits/hs_terminal.c
    else:
      source-dirs:
        - src
        - platform/posix/src
      include-dirs:
        - platform/posix/include
      c-sources:
        - platform/posix/cbits/hs_terminal.c

tests:
  terminal-test:
    main:                Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal
    - tasty
    - tasty-hunit
    - tasty-quickcheck

# executables:
#   terminal-ev:
#     main:                Main.hs
#     source-dirs:         example/terminal-ev
#     ghc-options:
#     - -Werror
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - terminal
#   terminal-out:
#     main:                Main.hs
#     source-dirs:         example/terminal-out
#     ghc-options:
#     - -Werror
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - terminal
#   terminal-printer:
#     main:                Main.hs
#     source-dirs:         example/terminal-printer
#     ghc-options:
#     - -Werror
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - terminal
#   terminal-screen:
#     main:                Main.hs
#     source-dirs:         example/terminal-screen
#     ghc-options:
#     - -Werror
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - terminal
