name:                terminal
synopsis:            Portable terminal interaction library
version:             0.1.0.0
github:              "lpeterse/terminal"
license:             BSD3
author:              "Lars Petersen"
maintainer:          "info@lars-petersen.net"
copyright:           "2018 Lars Petersen"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on Github at <https://github.com/lpeterse/terminal#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- exceptions
- stm
- text
- transformers
- prettyprinter

library:
  ghc-options: -Werror
  #-fwarn-incomplete-patterns
  exposed-modules:
    - Control.Monad.Repl
    - Control.Monad.Terminal
    - Control.Monad.Terminal.Color
    - Control.Monad.Terminal.Events
    - Control.Monad.Terminal.Pretty
    - Control.Monad.Terminal.Ansi
    - System.Terminal.Ansi
  other-modules:
    - Control.Monad.Terminal.Ansi.Internal
    - Control.Monad.Terminal.Ansi.AnsiTerminal
    - Control.Monad.Terminal.Ansi.AnsiTerminalT
    - System.Terminal.Ansi.Platform
  source-dirs: src
  when:
    - condition: os(windows)
      then:
        source-dirs:
          - platform/windows/src
        include-dirs:
          - platform/windows/include
        c-sources:
          - platform/windows/cbits/hs_terminal.c
      else:
        source-dirs:
          - platform/posix/src
        include-dirs:
          - platform/posix/include
        c-sources:
          - platform/posix/cbits/hs_terminal.c

executables:
  repl-demo:
    main:                Main.hs
    source-dirs:         app/repl-demo
    ghc-options:
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - terminal
  terminal-ev:
    main:                Main.hs
    source-dirs:         app/terminal-ev
    ghc-options:
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal
  terminal-out:
    main:                Main.hs
    source-dirs:         app/terminal-out
    ghc-options:
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal

tests:
  terminal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal
    - tasty
    - tasty-hunit
    - tasty-quickcheck
